#!/usr/bin/env bash
#
# Run all dotfiles setups.

set -e

cd "$(dirname $0)"

# find the installers and run them iteratively
find . -name setup.sh | while read installer ; do sh -c "${installer}" ; done
